(#148) Mypage target member information find function
penguinsAtEgloo/E-Gloo pull request #149
Opened 2021-09-24 05:08 UTC by dongyeon94

#148 
마이페이지 유저 조회 기능 추가

- 로그인할때 제공했던 token 활용 decoding해서 내부에 있는 user email로 조회

2021-09-24 05:38 UTC, upswp requested changes
수고하셨습니다 . 수정사항 요청 드립니다 ! 💯

2021-09-24 05:38 UTC, upswp commented on back-end-api/.gitignore
> +application.yaml
yaml git ignore 추가한 이유가 있을까요?

2021-09-24 05:38 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/member/dto/response/UserProfile.java
> +    private MemberRole role;
response DTO로 이용하시려구 UserProfile로 명명하신거같은데 저희 request, response에 대한 DTO member를 기준으로 하기로 하지 않았나요??

2021-09-24 05:38 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/member/service/MemberService.java
> +    }
토큰을 decoding해서 처리하게 된다면 JWT에 의존적으로 개발이 진행될 수 밖에 없게 됩니다. 

그렇기 때문에 Token은 현재 유저를 판별하는 최소 단위로 판별 단위로 처리를 가져가고 

만들어둔 @AuthUser 어노테이션 이용하셔서 유저 정보 가져오시게 된다면 email 정보 가져올 수 있습니다. 

그리고 해당 토큰을 decoding하는 코드는 테스트 코드로 들어가서 발급한 JWT가 올바르게 생성된 토큰인지 점검하는 쪽에 삽입되면 좋을 것 같습니다 !

2021-09-24 05:54 UTC, nobel6018 commented on back-end-api/.gitignore
> +application.yaml
저는 application.yaml로 써서
동연님께서 추가하신 내용도 좋은 거 같아요

2021-09-26 03:29 UTC, dongyeon94 commented
코드 리뷰 사항 적용
- response class 이름 변경
- token decode 방식에서 @AuthMember 방식으로 변경

2021-09-26 08:20 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/member/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long>{
`public interface MemberRepository extends JpaRepository<Member, Long> {`

띄워쓰기 있는 게 더 formatted 된 것이라 좋은 거 같습니다

포맷팅하시고 푸쉬해주시면 좋을 거 같습니다
intellij IDEA에서 단축키 cmd + option + L, 윈도우는 ctrl + alt + L 입니다

2021-09-26 08:30 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/member/controller/AuthController.java
> +    public ResponseEntity memberInfo(@AuthMember Member member) {
`ResponseEntity` -> `ResponseEntity<UserProfileResponse>`로 타입 명확하게 표기해주시면
Swagger 문서에서 Response Type을 추론(infer)해서 문서로 만들어주기 때문에 타입을 적어주시면 좋습니다

그리고 ResponseEntity가 generic class 이기 때문에 타입을 명확하게 적어주면 코드 품질도 올라갑니다

2021-09-26 15:05 UTC, dongyeon94 commented
코드 리뷰 사항 적용후 머지 진행합니다.
- return type 수정
- format 적용

2021-09-26 15:05 UTC, merged