(#31) ERD 변경으로 인한 검색기능 수정
penguinsAtEgloo/E-Gloo pull request #87
Opened 2021-08-11 16:33 UTC by dongyeon94

#31 
ERD 수정으로인한 레시피 검색 기능이 수정 되었습니다. 

Response
  - code
  - msg
  - error

## 
형태의 응답으로 작성되어 있으며 msg에 [] 타입으로 응답합니다.

레시피 검색 플로우는 그대로 가져갑니다.

||재료|레시피|
|------|---|---|
|1|김치|[김치찌개, 김치볶음밥, 김치전]|
|2|돼지고기|[김치찌개, 김치볶음밥, 삼겹살, 수육]|
|3|쌀|[김치볶음밥, 콩나물비빔밥]|

---
결과 
||추천 레시피|
|------|---|
|1|[김치볶음밥]|

2021-08-12 06:26 UTC, upswp requested changes
코드 컨벤션 적인 부분에서 수정할 부분이 필요합니다.

2021-08-12 06:26 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            List<Cooking> cooking_list = cookingRepository.findByIngredient(ingredient.get());
스네이크 표기법이라니 ...

2021-08-12 06:26 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            System.out.println(cooking_list.toString());
System.out.println 이라니...

2021-08-12 06:26 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            }
stream 으로 만들수 있지 않을까요?

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            List<Cooking> cooking_list = cookingRepository.findByIngredient(ingredient.get());
Ingredient와 Cooking을 fetch join으로 가지고 오는 게 좋아보입니다 (N+1문제)

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            List<Cooking> cooking_list = cookingRepository.findByIngredient(ingredient.get());
[Java code convention] cooking_list -> cookingList 또는 cookings 는 어떠신가요?

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            for(int j=0; j < cooking_list.size(); j++){
(가독성) stream().map()으로 구현하시는 건 어떨까요?

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +        return new ResponseEntityObject(ErrorCode.SUCCESS.getCode(), intersection(intersection).toString(),"");
Service level에서 ResponseEntity 반환하는 것보다 intersection만 던져주는 건 어떨까요?
ResponseEntity와 status code 처리는 Controller level에서 하는 게 역할에 맞다고 생각이 듭니다

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            System.out.println(cooking_list.toString());
slf4j 사용하셔서 log로 처리하는 건 어떨까요? 
local 개발에서 로그 확인하는 용도였으면 지우는 것도 좋아보이고
(dev나 production) 운영환경에서 log 남기시는 목적이시면 slf4j 사용하셔서 로그 남기시는 게 어떨까 합니다

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    @Autowired
필드 인젝션은 안티패턴입니다
consturctor injection 사용 부탁드립니다

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +            Optional<Ingredient> ingredient = ingredientRepository.findByName(ingredient_list.get(i).toString());
반복문을 사용하는 대신에 
findByNameIn 사용해야하는 거 아닐까합니다
(풀코드를 잘 모르고 정확한 문맥을 제가 잘 이해 못 한 것일수도 있어서 @빅상우님 교차 검증 부탁드립니다)
sql IN절을 사용해도 되는 부분이면
IN 절을 사용해서 한번에 처리하면 퍼포먼스 측면에서 많은 향상을 기대할 수 있을 거라 생각합니다

(.sql)
select *
from tb_ingredient
where name in ('name1', 'name2',,,)

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    public Object getRecipeByIngredients(ArrayList ingredient_list) {
Return 반환 타입이 Object는 유지보수성을 떨어뜨린다고 생각합니다 - Object는 모든 객체의 최상위 클래스이기 때문에 아무거나 반환해도 괜찮다라는 뜻입니다 정확한 반환 타입을 넣어주시면 좋을 거 같습니다

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    public Object getRecipeByIngredients(ArrayList ingredient_list) {
[java code convention] java에서 code convention을 지켜주시면 더 좋은 코드가 될 거라 생각합니다
class에서는 PascalCase
parameter, 인자값은 camelCase 입니다

(제안)
ingredient_list -> ingredientList 또는 ingredients, ingredientNames

2021-08-12 06:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    public Object getRecipeByIngredients(ArrayList ingredient_list) {
ArrayList ingredient_list

--> 
String... ingredientNames
ArrayList\<String\> ingredientNames

ingredient_list가 밑에 코드를 보니 String으로 ingredient names를 받는 코드로 보입니다
개발자의 의도를 좀 더 명확하게 위와 같이 입력받는 타입(ArrayList)을 바꾸는 건 어떠실까 생각이 들어서 제안드립니다

2021-08-12 16:16 UTC, dongyeon94 commented
코드리뷰 내용 적용하였습니다.

변경사항 입니다.
- code convention에 맞게 수정, 
- consturctor injection으로 수정
- 응답메시지를  기존 service에서 controller로 변경

아래 두 부분에 대해서는 아직 검색쪽에 적용된 로직에 성능 개선할때 진행하면 어떤가요?
아직 로직에 대한 고민이 많고 fetch join에 대해선 개인적인 스터디가 필요할 것 같습니다. 
- Fetch join
- 검색 요청 쿼리 관련

2021-08-12 17:35 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
> +    List<Ingredient> findByNameIn(ArrayList<String> ingredientList);
ArrayList<String> ingredientList

List<String> ingredientList
으로 타입 부모타입으로 쓰는 게 더 좋은 거 같습니다

구현타입(자식타입)을 사용하면 범용성과 범위가 좁아지기 때문에 반드시 ArrayList를 사용해야하는 경우가 아니라면 List가 더 좋은 선택이라고 생각합니다

2021-08-12 17:35 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
> +    List<Ingredient> findByNameIn(ArrayList<String> ingredientList);
변수명에 타입을 지정해주는 형식보다 좀 더 분명하게 
ingredients라고 사용하는 건 어떨까요?

IDE가 발전하지 않은 시절에는 타입(List)을 적어주는 게 좋은 코딩 스타일이었지만
변수명을 알려주는 건 IDE가 하게 하고 변수명에는 좀 더 의미가 분명하게 또는 잘 읽히게 적는 게 좋은 코딩 스타일이라고 생각합니다 (개발자 개인의 성향도 있어서 optional 선택지로 제안드리는 사항입니다)

2021-08-12 17:35 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    public Object getRecipeByIngredients(ArrayList<String> ingredientNameList) {
findByIngredientIn 을 사용해서 아래와 같이 처리하시는 건 어떨까요?
```
public List<Cooking> getRecipeByIngredients(List<String> ingredientNameList) {
    List<Ingredient> ingredientList = ingredientRepository.findByNameIn(ingredientNameList);

    return cookingRepository.findByIngredientIn(ingredientList);
}
```

2021-08-12 17:37 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
> +    public Object recipeByIngredients(@RequestParam ArrayList<String> ingredient){
return type에 Object를 사용하는 건 좋지 않다고 생각합니다
반환하는 타입(ResponseEntityObject)을 명확히 해주시면 더 좋은 코드가 될거라 생각합니다

2021-08-12 17:43 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
> +    public RecipeController(RecipeService recipeService){
아래와 같이 constructor 만들어주셔도 좋지만
Lombok을 도입했으니 Lombok을 활용하여 지루하게 반복되는 코드를 줄이는 게 좋을 거 같습니다

@RequiredArgsConstructor를 사용하시면 더욱 좋은 코드가 될것입니다

2021-08-12 17:43 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    }
Lombok @RequiredArgsConstructor을 사용하면 좋겠습니다

2021-08-12 17:45 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +    }
@RequiredArgsConstructor를 사용하면 좋은 점은 
(1) 반복되는 코드를 안써도 되는 점
(2) constructor injection해야할 필드가 추가/삭제되었을 경우 생성자를 변경하지 않아도 되는 점도 있습니다

2021-08-13 07:47 UTC, dongyeon94 commented
2차 코드리뷰 적용사항
-  @RequiredArgsConstructor 적용
- Arraylist 타입 List타입으로 변경
- 파라미터 및 return type 수정


상세한 코드리뷰 감사합니다.!! 👍 ✔️

2021-08-14 03:26 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
> +    List<Ingredient> findByNameIn(List<String> ingredients);
good!!

2021-08-14 03:26 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
> -
good!!

2021-08-14 03:26 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
> +        return new ResponseEntityObject(ErrorCode.SUCCESS.getCode(), recipeService.getRecipeByIngredients(ingredients).toString(),"");
good!!

2021-08-14 03:26 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
>      }
findByIngredientIn 을 사용해서 아래와 같이 처리하시는 건 어떨까요?

```
public List<Cooking> getRecipeByIngredients(List<String> ingredientNameList) {
    List<Ingredient> ingredientList = ingredientRepository.findByNameIn(ingredientNameList);

    return cookingRepository.findByIngredientIn(ingredientList);
}
```

2021-08-14 13:16 UTC, dongyeon94 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
>      }
제안해주신 방법을 사용하는 것을 고려해 보았는데 제안 주신 방법을 사용하면 
보유한 재료들로 할 수 있는 레시피 리스트의 합집합으로 결과가 도출됩니다. 

--- 

||재료|레시피|
|------|---|---|
|1|김치|[김치찌개, 김치볶음밥, 김치전]|
|2|돼지고기|[김치찌개, 김치볶음밥, 삼겹살, 수육]|


---
결과 
||추천 레시피|
|------|---|
|1|[김치찌개, 김치볶음밥, 김치전, 삼겹살, 수육]|


교집합의 결과 값인

결과 
||추천 레시피|
|------|---|
|1|[김치찌개, 김치볶음밥]|

의 도출을 원하고 있습니다.

2021-08-15 05:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
>      }
아하!! 그렇군요 도메인을 잘 몰랐습니다

2021-08-15 05:32 UTC, nobel6018 commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
>      }
저도 당장은 방법이 안 떠오릅니다 우선 이대로 진행하고 나중에 한 번 더 최적화하는 게 좋을 거 같습니다

2021-08-16 11:26 UTC, dongyeon94 commented
넵넵 코드리뷰 체크해주시면 머지 진행하겠습니다.

2021-08-17 01:41 UTC, upswp approved these changes
코드리뷰 반영 감사합니다! 머지하셔도 될것같습니다!

2021-08-17 01:41 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
>      }
👍🏻  수고하셨습니다

2021-08-17 01:41 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/ingredient/repository/IngredientRepository.java
> +    List<Ingredient> findByNameIn(List<String> ingredients);
수고하셨습니다!

2021-08-17 01:41 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/controller/RecipeController.java
> +        return new ResponseEntityObject(ErrorCode.SUCCESS.getCode(), recipeService.getRecipeByIngredients(ingredients).toString(),"");
👍🏻

2021-08-17 01:41 UTC, upswp commented on back-end-api/src/main/java/com/project/egloo/recipe/service/RecipeService.java
> +@RequiredArgsConstructor
LGTM 👍🏻

2021-08-17 07:22 UTC, merged