Login test 추가 (#68)
penguinsAtEgloo/E-Gloo pull request #88
Opened 2021-08-12 15:04 UTC by newtype94

# 로그인 테스트(Jest)

## 4가지 case

1. ID/PW pass
     - 맞는 ID/PW 입력 시 로그인 서버에서 status 200 응답 받는지 체크
2. ID/PW not pass
     - 틀린 ID/PW 입력 시 로그인 서버에서 status 400 응답 받는지 체크
3. index page when authorized
     - nuxt/auth 사용자 인증 되었을 때 index렌더링
4. index page when not authorized
     - nuxt/auth 사용자 인증 되지 않았을 때 index렌더링

2021-08-13 01:03 UTC, haewoniee requested changes
https://dev.to/bawa_geek/how-to-setup-jest-testing-in-nuxt-js-project-5c84

login은 컴포넌트가 아니라서 components.spec.js가 아닌 다른 파일에서 테스트 하셔야 할 것 같고, 위 링크에 있는 page testing과 component testing 차이 보시면 page는 routing으로 시작해야합니다. axios도 굳이 다시 구현할 필요 없이, login page에 구현되어있는 login button눌렀을때 실행되는 방식을 사용후 테스트하는것으로 바꿔주세요.

2021-08-13 01:03 UTC, haewoniee commented on front-end/test/Components.spec.js
> +    })
axios post 직접 쓰지말고 login에서 form채워서 click하는거 구현하시는게 좋을것같습니다.

2021-08-13 01:03 UTC, haewoniee commented on front-end/test/Components.spec.js
> +  });
https://dev.to/bawa_geek/how-to-setup-jest-testing-in-nuxt-js-project-5c84

login은 컴포넌트가 아니라서 components.spec.js가 아닌 다른 파일에서 테스트 하셔야 할 것 같고, 위 링크에 있는 page testing과 component testing 차이 보시면 page는 routing으로 시작해야합니다.

2021-08-17 13:18 UTC, newtype94 commented
로그인 테스트는 개발 서버 배포와 동시에 진행하기로 결정, 스프린트4로 연기

2021-08-17 13:18 UTC, closed without merging